name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: navigate to src and make
        run: |
          cd src
          make
      - name: setup atalanta
        run: |
          git clone https://github.com/hsluoyz/Atalanta.git
          cd Atalanta
          make
          cd ..
          mv Atalanta/ /home/codespace/Atalanta
      - name: run project
        run: |
          cd src
          ./project c17
